name: Release Docker image for the app

on:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: image-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push
        uses: byzanteam/jet-actions/fe-build-image@main
        with:
          registries: |-
            ${{ secrets.ALIYUN_SKYLARK_REGISTRY }}
            ghcr.io,byzanteam,${{ github.repository_owner }},${{ github.token }}
          cache_type: local
