name: Release Docker image for the app

on:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get APP_VSN
      run: |
        APP_VSN=$(awk -F '"' '/"version"/ { print $4 }' package.json)
        echo "::set-output name=APP_VSN::$APP_VSN"
      id: get-app-vsn

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: |
          APP_VSN=${{ steps.get-app-vsn.outputs.APP_VSN }}
        push: true
        tags: |
          ghcr.io/byzanteam/jet-home:${{ steps.get-app-vsn.outputs.APP_VSN }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
